// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA9VbXuISL6qkPbSLqYl7de7hLnjtzFFI',
    appId: '1:7920944655:web:bdd5b795773c4fa45bc57a',
    messagingSenderId: '7920944655',
    projectId: 'practiceflutterfirebase-1c3ec',
    authDomain: 'practiceflutterfirebase-1c3ec.firebaseapp.com',
    storageBucket: 'practiceflutterfirebase-1c3ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhGz17rpttMrrzn-DMkgO1FHZvuR-GBE',
    appId: '1:7920944655:android:2084c6c668da71495bc57a',
    messagingSenderId: '7920944655',
    projectId: 'practiceflutterfirebase-1c3ec',
    storageBucket: 'practiceflutterfirebase-1c3ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-Jr4BlMtTEMxadja2ycFZndERNIea2Q',
    appId: '1:7920944655:ios:5dc2b8cd918127005bc57a',
    messagingSenderId: '7920944655',
    projectId: 'practiceflutterfirebase-1c3ec',
    storageBucket: 'practiceflutterfirebase-1c3ec.appspot.com',
    iosClientId: '7920944655-iaqehro2ddbhs3junc162b507hibf69k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseownpractice',
  );
}
